// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfaEsEg1Eis3jaOjQmkxeRlTeBIJdhG6o',
    appId: '1:525508908544:web:12b6be4feacac113d42ae5',
    messagingSenderId: '525508908544',
    projectId: 'quicktime-d85b1',
    authDomain: 'quicktime-d85b1.firebaseapp.com',
    storageBucket: 'quicktime-d85b1.firebasestorage.app',
    measurementId: 'G-RLECTCK7XF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUlTNhzkTcVQiHXNaiotPR6TooWMqTcIM',
    appId: '1:525508908544:ios:9dfe7b99473c3bdbd42ae5',
    messagingSenderId: '525508908544',
    projectId: 'quicktime-d85b1',
    storageBucket: 'quicktime-d85b1.firebasestorage.app',
    iosClientId: '525508908544-48j1a4fr9ll4lullhs8hrqu8kji5frei.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickrun1web',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuWq5wFTOQJKD3xCH7K--aaRKGEDDsE5o',
    appId: '1:525508908544:web:a2bd7a72152ac933d42ae5',
    messagingSenderId: '525508908544',
    projectId: 'quicktime-d85b1',
    authDomain: 'quicktime-d85b1.firebaseapp.com',
    storageBucket: 'quicktime-d85b1.firebasestorage.app',
    measurementId: 'G-78PWEVLS1T',
  );
}
